/**
 * Pseudonym wordlists, shipped in the repository (PRD §7, §17).
 *
 * A student's label is their identity in the classroom, so both halves are
 * concrete, friendly and classroom-appropriate in each locale. Danish is a
 * translation in spirit rather than word-for-word: the adjective must inflect
 * naturally with the neuter/common gender of the noun it is paired with, so the
 * Danish nouns are all common gender (`en`-ord) and the adjectives are given in
 * the form that agrees with them.
 *
 * 48 x 48 = 2304 combinations per locale, which is ample for a classroom and
 * still small enough that every entry has been read.
 */

export interface Wordlist {
  readonly adjectives: readonly string[];
  readonly nouns: readonly string[];
}

const en: Wordlist = {
  adjectives: [
    "brave",
    "bright",
    "calm",
    "clever",
    "curious",
    "daring",
    "eager",
    "early",
    "fair",
    "fast",
    "gentle",
    "glad",
    "golden",
    "happy",
    "honest",
    "jolly",
    "keen",
    "kind",
    "lively",
    "loyal",
    "lucky",
    "merry",
    "mighty",
    "noble",
    "patient",
    "playful",
    "polite",
    "proud",
    "quick",
    "quiet",
    "ready",
    "sharp",
    "shiny",
    "silent",
    "smart",
    "smooth",
    "snowy",
    "steady",
    "sunny",
    "swift",
    "tidy",
    "true",
    "warm",
    "wise",
    "witty",
    "young",
    "zesty",
    "bold",
  ],
  nouns: [
    "otter",
    "heron",
    "falcon",
    "badger",
    "beaver",
    "puffin",
    "raven",
    "salmon",
    "hedgehog",
    "squirrel",
    "seal",
    "swan",
    "hare",
    "lynx",
    "marten",
    "moose",
    "owl",
    "pine",
    "birch",
    "willow",
    "maple",
    "clover",
    "harbour",
    "meadow",
    "island",
    "river",
    "fjord",
    "compass",
    "lantern",
    "anchor",
    "kite",
    "comet",
    "planet",
    "quartz",
    "amber",
    "opal",
    "cedar",
    "fern",
    "heather",
    "thistle",
    "sparrow",
    "starling",
    "swift",
    "wren",
    "dolphin",
    "narwhal",
    "walrus",
    "orca",
  ],
};

const da: Wordlist = {
  adjectives: [
    "modig",
    "lys",
    "rolig",
    "kløgtig",
    "nysgerrig",
    "dristig",
    "ivrig",
    "tidlig",
    "ærlig",
    "hurtig",
    "blid",
    "glad",
    "gylden",
    "munter",
    "oprigtig",
    "lystig",
    "skarp",
    "venlig",
    "livlig",
    "trofast",
    "heldig",
    "frisk",
    "mægtig",
    "ædel",
    "tålmodig",
    "leken",
    "høflig",
    "stolt",
    "kvik",
    "stille",
    "parat",
    "vaks",
    "skinnende",
    "tavs",
    "klog",
    "jævn",
    "snedækt",
    "stabil",
    "solrig",
    "rap",
    "ordentlig",
    "sand",
    "varm",
    "vis",
    "vittig",
    "ung",
    "krydret",
    "kæk",
  ],
  nouns: [
    "odder",
    "hejre",
    "falk",
    "grævling",
    "bæver",
    "lunde",
    "ravn",
    "laks",
    "pindsvin",
    "egern",
    "sæl",
    "svane",
    "hare",
    "los",
    "mår",
    "elg",
    "ugle",
    "fyr",
    "birk",
    "pil",
    "ahorn",
    "kløver",
    "havn",
    "eng",
    "ø",
    "flod",
    "fjord",
    "kompas",
    "lygte",
    "anker",
    "drage",
    "komet",
    "planet",
    "kvarts",
    "rav",
    "opal",
    "ceder",
    "bregne",
    "lyng",
    "tidsel",
    "spurv",
    "stær",
    "mursejler",
    "gærdesmutte",
    "delfin",
    "narhval",
    "hvalros",
    "spækhugger",
  ],
};

export const WORDLISTS = { en, da } as const;

export type WordlistLocale = keyof typeof WORDLISTS;

export function getWordlist(locale: WordlistLocale): Wordlist {
  return WORDLISTS[locale];
}
