import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import type { AppDatabase } from "./client";

/** Generated by `bunx drizzle-kit generate`, committed, and shipped in the image. */
export const MIGRATIONS_FOLDER = "drizzle";

/**
 * Apply pending migrations.
 *
 * Called at boot before the listener starts, so the operator never runs a
 * migration step (PRD §6). Tests call it against an in-memory database, which
 * is also what keeps the committed migrations honest: a schema change without a
 * generated migration fails the suite rather than production.
 */
export function applyMigrations(db: AppDatabase, folder: string = MIGRATIONS_FOLDER): void {
  migrate(db, { migrationsFolder: folder });
}
